# Núcleo de Python

Referencia básica: "Learning Scientific Programming with Python", Christian Hill. Cambridge University Press 2015. 

## ¿Qué es Python?

Python es un lenguaje de programación de propósito general diseñado por Guido van Rossum en 1989. Actualmente ocupa el cargo de "benevolente dictador vitalicio" en la estructura organizativa que mantiene y amplia el lenguaje. 

Es un lenguaje de programación de alto nivel porque evita que el usuario tenga que hacer las operaciones fundamentales a nivel de código máquina (por ejemplo escribir directamente las direcciones de memoria).

Se considera que es un lenguaje de nivel superior a C porque contiene una variedad sintáctica superior y también estructuras, listas, tuplas, conjuntos, diccionarios, que no están en C. Podemos aplicarnos la máxima de que *la vida es demasiado corta para programar en C*. 

En Python prima la idea de que *There should be one - and preferably only one - obvious way to do it*, frente a otros lenguajes de similar nivel como Ruby y Perl que tienden a considerar que *there's more than one way to do it*.

## Ventajas de Python

* Tiene una sintaxis bastante simple y clara. Se minimiza el riesgo de cometer errores  (bugs).  Los programas son fáciles de mantener y extender. 
* Es código libre en el doble sentido de que es gratuito (ventaja económica importante para la educación pública) y es de código abierto, lo que es condición necesaria para poder usarlo en la computación científica. 
* Es multiplataforma: podemos escribir programas que pueden correr en cualquier sistema operativo. 
* Python tiene su núcleo básico y además una gran librería de módulos y paquetes que extienden su aplicación a prácticamente cualquier ámbito de las ciencias y de la economía (véase la página [pypi.python.org/pypi](http://pypi.python.org/pypi)). También se utiliza para la programación de páginas web y para gestión de bases de datos. 
* Es fácil de aprender y sus mensajes de error permiten identificar con claridad los fallos cometidos.
* Es un lenguaje flexible (multi-paradigma): contiene las mejores estructuras de los lenguajes de procedimiento, de lenguajes orientados a objetos y de los lenguajes funcionales.


## Desventajas de Python

* La velocidad de ejecución es menor que la de los lenguajes compilados (C o Fortran). Sin embargo esta desventaja se alivia por una mayor velocidad en la elaboración de los programas y en el caso de la programación científica, podemos recurrir a los paquetes Numpy y SciPy.
* Es un código difícil de evitar que lo plagien. 
* Ha tenido un desarrollo "difícil" asociado a la incompatibilidad entre las versiones 2 y 3. 

## Instalación

La página web oficial de Python es `www.python.org` y allí podemos encontrar cómo descargar e instalar Python y los paquetes que necesitemos.
La instalación más cómoda y efectiva es a través del paquete *Anaconda* que se puede descargar desde la página `http://continuum.io/downloads`. Se puede elegir entre la versión 2 o 3 de Python, pero nosotros usaremos la 3.

En la instalación de *Anaconda* se incluye:

* Notebooks de Jupyter: estos apuntes se han redactado con esta aplicación.
* Spyder: editor de código que incluye también Ipython.
* Ipython: ventana de comandos para interaccionar directamente con el kernel. 

Nosotros vamos a usar los notebooks de Jupyter como herramienta de desarrollo.

## Notebooks de Jupyter

Utiliza el lenguaje Markdown para generar celdas de texto. 

Los comandos básicos de este lenguaje son:

* Itálica: `*texto*` 
* Negrita: `**texto**`
* Anchura fija: `texto` (Acento grave)
* URLs: [URL text] (http://www.example.com)
* Nuevo párrafo: Línea en blanco
* Verbatim: Texto con cuatro espacios
* Tablas: | para las columnas y |— para las filas (son tres guiones)
* Línea horizontal: —
* Nivel 1 de cabecera: #
* Nivel 2 de cabecera: ## etc.
* Bloque de cita textual: >
* Listas sin números: *
* Listas con ordinales: 1., 2., etc.
* Imágenes: ! [Texto alternativo] (fichero-imagen.png)
* Ecuaciones latex: ``` $, $$```

Para los gráficos conviene incluir la sentencia:
%matplotlib inline

## Datos en Python

Hay tres categorías (`type`) de datos en Python: números, cadenas de caracteres (`str`) y valores lógicos (`bool`). Dentro de los números hay tres tipos (`type`): enteros (`int`), reales (`float`) y complejos (`complex`).

Los enteros pueden tener cualquier longitud (limitada por la memoria del ordenador) y ser positivos o negativos. Se puede convertir al tipo entero con el constructor `int()`.

Los reales se definen mediante el punto decimal y también usando notación científica (`E` o `e`). Se puede convertir al tipo real con el contructor `float()`.

Los complejos se definen añadiendo `j` a su parte imaginaria. Partes real e imaginaria se tratan como reales. Se puede convertir al tipo complejo con el contructor `complex()`. 

In [1]:
3+4j

(3+4j)

In [2]:
print(type(3),type(5.),type(5E3),type(5e3),'\n', type(1+1j))

<class 'int'> <class 'float'> <class 'float'> <class 'float'> 
 <class 'complex'>


En Python, todo es un objeto que pertenece a una clase. De ahí que aparezca en la salida anterior la palabra `class`.

In [3]:
print(int(3.4),int(-3.6),float(3), complex(3,1))

3 -3 3.0 (3+1j)


## Operadores aritméticos básicos

* `+` Suma
* `-` Resta
* `*` Multiplicación
* `/` División en coma flotante
* `//` División entera
* `%` Resto de la división
* `**` Exponenciación 

La mezcla de tipos (int, float) genera float. La división en coma flotante siempre genera float. La división entera entre enteros genera entero. El resto de división entre enteros genera entero.

La preferencia de operadores es (de mayor a menor): `**, (*,/,//,%), (+,-)`. En caso de igualdad se ejecuta de izquierda a derecha, excepto la exponenciación que es al revés. En caso de duda lo más resolutivo es usar paréntesis.

In [4]:
print(8/4/2,8/(4/2),3**3**2,3**9,(3**3)**2)

1.0 4.0 19683 19683 729


## Funciones, métodos y atributos matemáticos

Las funciones y los métodos son muy similares en cuanto a resultados, pero a nivel interno de Python son muy diferentes. Los números en Python son objetos, pertenecen a una clase, y en cada clase se definen atributos y métodos.

Por ejemplo, un número complejo tiene parte real y parte imaginaria. Podemos obtener cada una usando los atributos `.real` y `.imag`. Sin embargo el conjugado de un número complejo se obtiene usando el método `.conjugate()`. Como vemos los atributos no tienen paréntesis, mientras que los métodos sí. Tanto atributos como métodos tienen la sintaxis de nombre del objeto, seguido de un punto y nombre del atributo o método.

Sin embargo el valor absoluto de un número o su redondeo se obtienen a partir de la aplicación de unas funciones al objeto: `abs()` y `round()`.

Para las funciones matemáticas que vienen definidas en cualquier calculadora científica necesitamos importar el paquete `math`. La lista de funciones se puede consultar en [https://docs.python.org/3/library/math.html#module-math](https://docs.python.org/3/library/math.html#module-math). 

Algunas de las más usadas son: `sqrt, exp, log, log10, sin, cos, tan, asin, acos, atan, factorial, degrees, radians`. También incluye, entre otras constantes, los números `e` y `pi`.

Para importar el paquete usamos la instrucción `import math`.

In [5]:
print((3+7j).real,(3+7j).imag,(3+7j).conjugate(),abs(-3.4),
      round(2.5),round(3.5))

3.0 7.0 (3-7j) 3.4 2 4


In [6]:
import math
print(math.sqrt(16), math.sqrt(16.0),
      math.degrees(math.acos(1/2)))

4.0 4.0 59.99999999999999


## Variables

El concepto de variable es común a todos los lenguajes de programación, pero el uso o significado para cada uno puede ser muy diferente. En Python, una variable es como una etiqueta o identificador de una dirección de memoria donde se ubica uno o más datos. No se trata por tanto de un contenedor de dato sino de una etiqueta.

Veamos el siguiente ejemplo:

In [7]:
a=3  # Se crea el objeto int 3 y una etiqueta llamada a
print('El valor de a es ',a)

El valor de a es  3


En la primera línea se crea un objeto de tipo entero en alguna localización de memoria y a esta dirección se le llama `a`. A continuación, en la segunda línea mostramos el valor que hay almacenado en `a` usando la función `print()`.

En Python no hay que especificar qué tipo de dato identifica una variable. Es lo que se llama asignación dinámica. 

Para asignar nombre a una variable seguiremos la siguiente regla: debe comenzar por una letra y puede contener letras, números y el guión bajo. Se diferencia entre mayúsculas y minúsculas. Hay que evitar los nombres reservados para los comandos. Hay que tener cuidado con l y 1 y O y 0 porque son difíciles de distiguir. Hay que intentar usar nombres que tengan significado, pero hay que evitar nombres excesivamente largos.

## Operadores de comparación y variables lógicas

Los operadores de comparación son:

* `==` igual
* `!=` distinto
* `>` mayor que
* `<` menor que
* `>=` mayor o igual que
* `<=` menor o igual que

Cuando se efectua una comparación se genera un objeto de tipo booleano que puede tener dos valores, `True` o `False`.

In [8]:
import math  # importamos el paquete math
a=3  # definimos el entero 3 y lo etiquetamos con a
b=math.pi  # definimos el numero pi y lo etiquetamos con b
a>=b 

False

Hay que tener mucho cuidado de no confundir `=` con `==`. El primero es asignación y el segundo es comparación. El primero no genera salida y el segundo genera un objeto booleano.

En las comparaciones con float hay que tener cuidado con las aproximaciones binarias de los números.

In [9]:
a=0.01
b=0.1**2
print(abs(a-b)<0.0000000000000001,a==b)

True False


## Operadores lógicos

In [10]:
print(not 7.5 < 0.9 and 4 == 4,
      not (7.5 < 0.9 or 4 == 4))

True False


## Cadenas de caracteres

Es una secuencia ordenada, e inmutable, de caracteres definida entre '' o "". 

Se puede seleccionar un elemento concreto de la cadena añadiendo `[n]`, donde `n` es la posición. En Python la numeración de una secuencia ordenada empieza con el 0. 

In [11]:
print('Tierra a la vista', 'Diego de Triana'[0])

Tierra a la vista D


Las cadenas se pueden sumar entre sí, lo que significa superposición, o multiplicar por un entero, lo que implica superponerla un número de veces igual al entero.

También podemor saber su longitud con la función `len(cadena)` donde `cadena` es la cadena de caracteres.

In [12]:
a='abc'
b='345'
print(a+b,b*3, len(a))

abc345 345345345 3


### Seleccionando trozos de cadena

Para seleccionar un elemento de una cadena se utiliza el indexador `[]`.

Para seleccionar un trozo utilizamos la forma `[f:l]` donde `f` es el primer elemento, incluido, y `l` es el último, excluido. Por defecto `f` es cero y `l` es hasta el final. Es decir, se selecciona un número de elementos dado por `l-f`. De forma inversa, si se parte del elemento `f` y se quieren seleccionar `r` elementos se usaría `[f:f+r]`.

Si el índice es negativo se empieza a contar desde la última posición.

In [13]:
a='Enigma'
print(a[0],a[-2], a[1:3], a[:3], a[1:], a[1:-1])

E m ni Eni nigma nigm


Para saber si una cadena está en otra se puede usar el operador `in`.

In [14]:
a='Don Quijote de la Mancha'
'Quijote' in a

True

## Listas

Es un conjunto ordenado y mutable de objetos encerrados entre corchetes. 
La lista vacía se define como `[]`.

Cada elemento de la lista se selecciona con el nombre de la lista seguido con la posición del objeto encerrado entre corchetes.

También se puede crear con el contructor `list()`.

In [15]:
a=[1,2,3,[4,5],'a',False]
print(a[0],a[3],a[3][0],a[-1])

1 [4, 5] 4 False


El trozo de lista se hace una copia. Se copian listas usando `b=a[:]`.

In [6]:
a=[1,2,3,4,5,6,7]
c=a
d=list(a)
b=a[0:3]
print(a[1],b[1])
a[1]=3
print(a[1],b[1],c[1],d[1])

2 2
3 2 3 2


Podemos usar el comodín `-1` para indicar el último elemento de la lista y también para indicar un incremento negativo (se cambia el orden):

In [17]:
print(a[::-1])
print(a[-1])

[7, 6, 5, 4, 3, 3, 1]
7


Los métodos habituales que actúan sobre las listas son:

* `append(elem)`  Añade `elem` al final de la lista
* `sort()` Ordena la lista
* `count(elem)` Devuelve el número de elementos igual a `elem`

In [3]:
a=[1,2,3,4,5,6]
print(a)
a.reverse()
print(a)
a.sort()
print(a)
print(a.count(5))


[1, 2, 3, 4, 5, 6]
[6, 5, 4, 3, 2, 1]
[1, 2, 3, 4, 5, 6]
1


## Tuplas

En muchos aspectos son como listas pero con carácter inmutable. Se definen poniendo elementos entre paréntesis y separados por comas. El constructor es `tuple()`. Se pueden seleccionar elementos o trozos de forma análoga a listas, pero no se puede modificar ningún elemento, ni añadir ni eliminar. Pueden contener elementos mutables como listas:

In [19]:
t=(1,2,3,[4,5],6)
print(t[3],t[3][0])

[4, 5] 4


Una tupla con un solo elemento, singleton, se define con una coma añadida para evitar confusión con el uso sintáctico de los paréntesis:

In [20]:
t1=(1,)
t2=tuple('abc')
print(t1,t2)

(1,) ('a', 'b', 'c')


## El tipo `range`

Para generar una progresión aritmética de enteros se usa el constructor `range` con tres posibles argumentos: entero inicial, entero final y el incremento. 

El objeto creado por `range` NO es una lista, sino un objeto iterable en el que se puede seleccionar cada elemento:

In [21]:
a=range(3,6)
b=range(2,10,2)
print(a, a[0],b[-1],len(a),len(b),'\n',list(a))

range(3, 6) 3 8 3 4 
 [3, 4, 5]


## Bucles `for`

Hasta ahora los programas se ejecutan de forma secuencial, es decir, una línea detrás de otra. Pero un programa puede necesitar ejecutar sentencias un número determinado de veces, o ejecutar una sentencia u otra en función del valor de una variable, etc. Para ello están los bucles `for` y `while` y las estructuras de control `if-elif-then`.

El bucle `for` ejecuta una serie de sentencias para cada uno de los miembros de un iterable. La sintaxis se ve en el ejemplo. El cuerpo debe estar indentado, siendo 4 espacios en blanco lo recomendable. La variable índice se hace global y adquiere el valor último del bucle. Se pueden anidar bucles.

Un ejemplo puede ser el cálculo del valor medio de una lista de números:

In [22]:
a=[1,2,3,4,5]
vm=0.
for i in a:
    vm=i+vm
vm=vm/len(a)
print(vm)
print(i)

3.0
5


También se puede utilizar el tipo `range` para darle valores a la variable de iteración:

In [23]:
for i in range(1,6):
    print(i**2, end=' ')
print(i)

1 4 9 16 25 5


También se puede usar una cadena de caracteres como lista para valores del iterador:

In [6]:
li='esta es la historia de ...'
for i in li:
    print(i,end=',')

e,s,t,a, ,e,s, ,l,a, ,h,i,s,t,o,r,i,a, ,d,e, ,.,.,.,

## Estructura `if-elif-else`

Permite ir cambiando la dirección del flujo del programa en función de si son ciertas o no las condiciones establecidas. Si la sentencia que acompaña a `if` es cierta, se ejecuta el cuerpo indentado y se pasa a la sentencia siguiente de la estructura, si es falsa se pasa al siguiente `elif` donde se ejecuta el cuerpo indentado si es cierta y se pasa a la siguiente sentencia fuera de la estructura, y así para cada uno de los `elif` hasta el `else` que se ejecuta siempre que se llegue a él.

In [25]:
for i in range(10):
    if i%2 ==0:
        print(i,' es par')
    else: 
        print(i,' es impar')

0  es par
1  es impar
2  es par
3  es impar
4  es par
5  es impar
6  es par
7  es impar
8  es par
9  es impar


In [26]:
for i in range(10):
    if i<=3:
        print(i,' es menor o igual que 3')
    elif i<=5:
        print(i,' es menor o igual que 5 pero mayor que 3')
    elif i<=7:
        print(i,' es menor o igual que 7 pero mayor que 5')
    else:
        print(i,' es mayor que 7')

0  es menor o igual que 3
1  es menor o igual que 3
2  es menor o igual que 3
3  es menor o igual que 3
4  es menor o igual que 5 pero mayor que 3
5  es menor o igual que 5 pero mayor que 3
6  es menor o igual que 7 pero mayor que 5
7  es menor o igual que 7 pero mayor que 5
8  es mayor que 7
9  es mayor que 7


## Bucle `while`

Es un tipo de bucle que se repite hasta que la sentencia de control toma el valor de `False`. Por ejemplo, para encontrar el máximo común divisor podemos usar el algoritmo de Euclides a través de un bucle `while`:

In [27]:
a,b=25, 15
while b!=0:
    a,b=b,a%b
print(a)

5


## Funciones

Es una herramienta muy útil en la programación. De hecho hay una característica de los diferentes lenguajes de programación que es la funcionalidad, e indica la capacidad del lenguaje en el uso de funciones.

Una función se define con la sentencia `def` seguida del nombre de la función y entre paréntesis los diferentes parámetros o argumentos que utiliza, y para finalizar la línea de definición, los dos puntos que nos indica una indentación del cuerpo de la función. 

Una función termina habitualmente con la sentencia `return` seguida de las variables de salida separadas por comas, en forma de tupla.

Para llamar a la función se usa su nombre seguido por el valor de las variables entre paréntesis.

In [28]:
def cuadrado(x):
    """Devuelve el cuadrado de un numero"""
    return x**2
print(cuadrado(3))

9


* Una función no puede ser llamada antes de ser definida
* El uso de una función se debe documentar a través de las docstring: como primera línea del cuerpo de la función y encerradas entre triple comillas. Toda función tiene el atributo `.__doc__` que devuelve la docstring. Se debe documentar el uso, pero la explicación del algoritmo es mejor hacerlo con #.

In [29]:
cuadrado.__doc__

'Devuelve el cuadrado de un numero'

Los argumentos se pueden pasar a una función de dos maneras: por la posición o a través de nombre. En el primer caso hay que respetar el orden en la definición y en el segundo caso el nombre. Si se mezclan los tipos, hay que poner primero los definidos por posición. 

In [30]:
def f(x,y,z):
    if z<0:
        xi=x+y+z
    else:
        xi=x*y*z
    return xi**2
print(f(1,2,-3),f(y=4,z=-3,x=1))

0 4


## Ficheros

El acceso a un fichero se hace a través del objeto `file` que se crea con la función `open(path,modo)` donde `path` indica la ubicación y nombre del fichero, y `modo` indica el tipo de acceso:

* `r`  solo lectura
* `w`  solo escritura (sobreescribiendo)
* `a`  solo escritura (añadiendo a un fichero ya existente)

Una vez terminado con el fichero hay que cerrarlo con el método `.close()`.

El objeto `file` es iterable.

### Escritura

Se puede hacer con `.write(cadena)`, donde `cadena` es una cadena de caracteres.
También se puede usar la sentencia `print`, con el argumento `file`. 

In [31]:
f=open('kk.txt','w')
a=3
f.write('kk\n')
print('El valor de a es {}'.format(a), file=f)
f.close()

In [32]:
f=open('kk2.txt','w')
for i in range(1,1001):
    print(i,i**2,i**3,sep=', ',file=f)
f.close()

### Lectura

* `.readline()` lee una sola línea en forma de cadena de caracteres
* `.readlines()` genera una lista con cada una de las líneas

In [33]:
f=open('kk.txt','r')
for line in f:
    print(line,end='')
f.close()

kk
El valor de a es 3


In [34]:
numero=[]
cuadra=[]
cubo=[]
f=open('kk2.txt','r')
for line in f:
    campos=line.split(',')
    numero.append(int(campos[0]))
    cuadra.append(int(campos[1]))
    cubo.append(int(campos[2]))
f.close()
print(numero[499]-1,cuadra[499],cubo[499])

499 250000 125000000


In [35]:
f=open('kk2.txt','r')
todas=f.readlines()
f.close()
print(todas[499])

500, 250000, 125000000



Cuando se lee una cadena de caracteres y se quiere evaluar su contenido se puede usar la función `eval()`:

In [36]:
a=eval('(33,)')
type(a)

tuple

## Mutable e inmutable

Los arrays de numpy son objetos mutables. Obsérvese el siguiente código:

In [2]:
reset

Once deleted, variables cannot be recovered. Proceed (y/[n])? y


In [3]:
import numpy as np
a=3
b=a
print(a,b)
a=4
print(a,b)
b=2
print(a,b)
d=np.zeros((3,3),float)
#e=np.zeros(3,float)
f=np.zeros(3,float)
d[0,0]=14
e=d[:,0]
f[:]=d[:,0]
print(d,e,f)
d[0,0]=13
print(d,e,f)

3 3
4 3
4 2
[[14.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]] [14.  0.  0.] [14.  0.  0.]
[[13.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]] [13.  0.  0.] [14.  0.  0.]
